# Generated by Django 3.1.5 on 2022-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20221130_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
