# Generated by Django 3.1.5 on 2022-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20221130_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('FırınUrunleri', 'Fırın Ürünleri'), ('AdetUrunleri', 'Adet Ürünler'), ('Borek', 'Börek'), ('Icecek', 'İçecek'), ('Kahvalt', 'Kahvaltı'), ('Sandvic', 'Sandvic'), ('Meze', 'Meze'), ('Tatlı', 'Tatlı'), ('SerbetliTatlı', 'Şerbetli Tatlı')], max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
